"""
Framework-agnostic DAO protocol interfaces.

All DAO protocols depend on DatabaseSession, NOT on any specific ORM.
Service layer and API layer code exclusively against these protocols.
"""

from datetime import datetime
from typing import Any, Dict, List, Optional, Protocol
from uuid import UUID

from dao_service.core.database import DatabaseSession
from dao_service.schemas.conversation import ConversationCreateDTO, ConversationDTO, ConversationUpdateDTO
from dao_service.schemas.goal import GoalCreateDTO, GoalDTO, GoalUpdateDTO
from dao_service.schemas.notification_log import (
    NotificationLogCreateDTO,
    NotificationLogDTO,
    NotificationLogUpdateDTO,
)
from dao_service.schemas.pattern import PatternCreateDTO, PatternDTO, PatternUpdateDTO
from dao_service.schemas.task import TaskCreateDTO, TaskDTO, TaskUpdateDTO
from dao_service.schemas.user import UserCreateDTO, UserDTO, UserUpdateDTO


# --- Base CRUD Protocol ---


class BaseDAOProtocol(Protocol):
    """Minimum CRUD contract all DAOs must satisfy."""

    async def get_by_id(self, db: DatabaseSession, id: UUID) -> Optional[Any]: ...
    async def get_multi(self, db: DatabaseSession, skip: int, limit: int) -> List[Any]: ...
    async def count(self, db: DatabaseSession) -> int: ...
    async def delete(self, db: DatabaseSession, id: UUID) -> bool: ...


# --- Entity-specific Protocols ---


class UserDAOProtocol(Protocol):
    async def create(self, db: DatabaseSession, obj_in: UserCreateDTO) -> UserDTO: ...
    async def get_by_id(self, db: DatabaseSession, id: UUID) -> Optional[UserDTO]: ...
    async def get_multi(self, db: DatabaseSession, skip: int, limit: int) -> List[UserDTO]: ...
    async def count(self, db: DatabaseSession) -> int: ...
    async def update(self, db: DatabaseSession, id: UUID, obj_in: UserUpdateDTO) -> Optional[UserDTO]: ...
    async def delete(self, db: DatabaseSession, id: UUID) -> bool: ...


class GoalDAOProtocol(Protocol):
    async def create(self, db: DatabaseSession, obj_in: GoalCreateDTO) -> GoalDTO: ...
    async def get_by_id(self, db: DatabaseSession, id: UUID) -> Optional[GoalDTO]: ...
    async def get_multi(self, db: DatabaseSession, skip: int, limit: int) -> List[GoalDTO]: ...
    async def count(self, db: DatabaseSession) -> int: ...
    async def update(self, db: DatabaseSession, id: UUID, obj_in: GoalUpdateDTO) -> Optional[GoalDTO]: ...
    async def delete(self, db: DatabaseSession, id: UUID) -> bool: ...


class TaskDAOProtocol(Protocol):
    """Framework-agnostic task DAO interface with custom Scheduler/Observer queries."""

    # Standard CRUD
    async def create(self, db: DatabaseSession, obj_in: TaskCreateDTO) -> TaskDTO: ...
    async def get_by_id(self, db: DatabaseSession, id: UUID) -> Optional[TaskDTO]: ...
    async def get_multi(self, db: DatabaseSession, skip: int, limit: int) -> List[TaskDTO]: ...
    async def count(self, db: DatabaseSession) -> int: ...
    async def update(self, db: DatabaseSession, id: UUID, obj_in: TaskUpdateDTO) -> Optional[TaskDTO]: ...
    async def delete(self, db: DatabaseSession, id: UUID) -> bool: ...

    # Custom methods for Scheduler microservice
    async def get_tasks_by_user_and_timerange(
        self, db: DatabaseSession, user_id: UUID, start_at: datetime, end_at: datetime
    ) -> List[TaskDTO]: ...

    async def bulk_update_status(self, db: DatabaseSession, task_ids: List[UUID], new_status: str) -> int: ...

    # Custom methods for Observer microservice
    async def get_task_statistics(
        self, db: DatabaseSession, user_id: UUID, start_date: datetime, end_date: datetime
    ) -> Dict[str, Any]: ...


class ConversationDAOProtocol(Protocol):
    async def create(
        self, db: DatabaseSession, obj_in: ConversationCreateDTO
    ) -> ConversationDTO: ...
    async def get_by_id(self, db: DatabaseSession, id: UUID) -> Optional[ConversationDTO]: ...
    async def get_multi(
        self, db: DatabaseSession, skip: int, limit: int
    ) -> List[ConversationDTO]: ...
    async def count(self, db: DatabaseSession) -> int: ...
    async def update(
        self, db: DatabaseSession, id: UUID, obj_in: ConversationUpdateDTO
    ) -> Optional[ConversationDTO]: ...


class PatternDAOProtocol(Protocol):
    async def create(self, db: DatabaseSession, obj_in: PatternCreateDTO) -> PatternDTO: ...
    async def get_by_id(self, db: DatabaseSession, id: UUID) -> Optional[PatternDTO]: ...
    async def get_multi(self, db: DatabaseSession, skip: int, limit: int) -> List[PatternDTO]: ...
    async def count(self, db: DatabaseSession) -> int: ...
    async def update(
        self, db: DatabaseSession, id: UUID, obj_in: PatternUpdateDTO
    ) -> Optional[PatternDTO]: ...
    async def delete(self, db: DatabaseSession, id: UUID) -> bool: ...


class NotificationLogDAOProtocol(Protocol):
    async def create(self, db: DatabaseSession, obj_in: NotificationLogCreateDTO) -> NotificationLogDTO: ...
    async def get_by_id(self, db: DatabaseSession, id: UUID) -> Optional[NotificationLogDTO]: ...
    async def get_multi(
        self, db: DatabaseSession, skip: int, limit: int
    ) -> List[NotificationLogDTO]: ...
    async def count(self, db: DatabaseSession) -> int: ...
    async def update(
        self, db: DatabaseSession, id: UUID, obj_in: NotificationLogUpdateDTO
    ) -> Optional[NotificationLogDTO]: ...
    async def delete(self, db: DatabaseSession, id: UUID) -> bool: ...
