/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/chat/message": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Send Message
     * @description 17.1.1–17.1.4 — Accept a user message, run the LangGraph agent, persist
     *     results to DB, and return the assistant reply with metadata.
     */
    post: operations["send_message_api_v1_chat_message_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/chat/history": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get History
     * @description 17.1.3 — Return paginated message history for a conversation, oldest first.
     */
    get: operations["get_history_api_v1_chat_history_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/goals/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Goals
     * @description 17.2.1 — List goals; include pipeline sub-goals as nested array.
     */
    get: operations["list_goals_api_v1_goals__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/goals/{goal_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Goal
     * @description 17.2.2 — Fetch a single goal by ID; verify ownership.
     */
    get: operations["get_goal_api_v1_goals__goal_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/goals/{goal_id}/abandon": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Abandon Goal
     * @description 17.2.3 — Mark goal as abandoned and cancel its exclusive pending tasks.
     */
    patch: operations["abandon_goal_api_v1_goals__goal_id__abandon_patch"];
    trace?: never;
  };
  "/api/v1/goals/{goal_id}/modify": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Modify Goal
     * @description 17.2.4 — Invoke the LangGraph agent with a MODIFY_GOAL intent.
     */
    patch: operations["modify_goal_api_v1_goals__goal_id__modify_patch"];
    trace?: never;
  };
  "/api/v1/goals/{goal_id}/tasks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Goal Tasks
     * @description 17.2.5 — Return all tasks belonging to a goal.
     */
    get: operations["get_goal_tasks_api_v1_goals__goal_id__tasks_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tasks/today": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Today Tasks
     * @description 17.3.1 — Return pending tasks scheduled for today in the user's local timezone.
     */
    get: operations["get_today_tasks_api_v1_tasks_today_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tasks/{task_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Task
     * @description 17.3.2 — Fetch a single task by ID; verify ownership.
     */
    get: operations["get_task_api_v1_tasks__task_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tasks/{task_id}/complete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Complete Task
     * @description 17.3.3 — Mark a task as done. If it is the last pending task on its goal,
     *     mark the goal completed and activate the next pipeline goal if present.
     */
    patch: operations["complete_task_api_v1_tasks__task_id__complete_patch"];
    trace?: never;
  };
  "/api/v1/tasks/{task_id}/missed": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Missed Task
     * @description 17.3.4 — Mark a task as missed and trigger the pattern observer asynchronously.
     */
    patch: operations["missed_task_api_v1_tasks__task_id__missed_patch"];
    trace?: never;
  };
  "/api/v1/tasks/{task_id}/reschedule": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reschedule Task
     * @description 17.3.5 — Run the LangGraph agent with a RESCHEDULE_TASK intent.
     */
    post: operations["reschedule_task_api_v1_tasks__task_id__reschedule_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/analytics/overview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Overview */
    get: operations["get_overview_api_v1_analytics_overview_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/analytics/goals": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Goals Progress */
    get: operations["get_goals_progress_api_v1_analytics_goals_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/analytics/missed-by-cat": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Missed By Category */
    get: operations["get_missed_by_category_api_v1_analytics_missed_by_cat_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/analytics/weekly": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Weekly Stats */
    get: operations["get_weekly_stats_api_v1_analytics_weekly_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/patterns/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Patterns
     * @description 17.5.1
     */
    get: operations["list_patterns_api_v1_patterns__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/patterns/{pattern_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Pattern
     * @description 17.5.2
     */
    get: operations["get_pattern_api_v1_patterns__pattern_id__get"];
    put?: never;
    post?: never;
    /**
     * Delete Pattern
     * @description 17.5.4 — Hard delete; return HTTP 204.
     */
    delete: operations["delete_pattern_api_v1_patterns__pattern_id__delete"];
    options?: never;
    head?: never;
    /**
     * Patch Pattern
     * @description 17.5.3 — Set data.user_overridden=true when user_override is provided.
     */
    patch: operations["patch_pattern_api_v1_patterns__pattern_id__patch"];
    trace?: never;
  };
  "/api/v1/account/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Me
     * @description 17.6.1
     */
    get: operations["get_me_api_v1_account_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Patch Me
     * @description 17.6.2
     */
    patch: operations["patch_me_api_v1_account_me_patch"];
    trace?: never;
  };
  "/api/v1/account/phone/verify/send": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Phone Verify Send
     * @description 17.6.3
     */
    post: operations["phone_verify_send_api_v1_account_phone_verify_send_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/account/phone/verify/confirm": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Phone Verify Confirm
     * @description 17.6.4
     */
    post: operations["phone_verify_confirm_api_v1_account_phone_verify_confirm_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/account/whatsapp/opt-in": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Whatsapp Opt In
     * @description 17.6.5
     */
    post: operations["whatsapp_opt_in_api_v1_account_whatsapp_opt_in_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/account/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete Account
     * @description 17.6.6 — GDPR erasure: cascade-delete all user data.
     */
    delete: operations["delete_account_api_v1_account__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/account/export": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Export Account
     * @description 17.6.7 — GDPR portability: return all user data as JSON.
     */
    get: operations["export_account_api_v1_account_export_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/webhooks/twilio/whatsapp": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Twilio Whatsapp Webhook
     * @description 17.7.2 — Parse WhatsApp reply and update task status.
     */
    post: operations["twilio_whatsapp_webhook_api_v1_webhooks_twilio_whatsapp_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/webhooks/twilio/voice": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Twilio Voice Webhook
     * @description 17.7.3 — Parse DTMF digits and update task status.
     */
    post: operations["twilio_voice_webhook_api_v1_webhooks_twilio_voice_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/demo/trigger-location": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Trigger Location
     * @description 17.8.1 — Fire push notifications for all pending location-triggered tasks.
     */
    post: operations["trigger_location_api_v1_demo_trigger_location_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/_echoconfig": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Echoconfig
     * @description Returns the full resolved config.
     *
     *     - Pydantic settings (sourced from .env / env vars) are always shown.
     *     - In non-development environments every os.environ entry is also included
     *       so variables injected at the platform level (e.g. Railway, Render, Fly)
     *       are visible alongside the declared settings.
     */
    get: operations["echoconfig__echoconfig_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AccountMeResponse */
    AccountMeResponse: {
      /** Id */
      id: string;
      /** Email */
      email?: string | null;
      /** Timezone */
      timezone?: string | null;
      /** Onboarded */
      onboarded?: boolean | null;
      /** Phone Verified */
      phone_verified?: boolean | null;
      /** Notification Preferences */
      notification_preferences?: {
        [key: string]: unknown;
      } | null;
      /** Monthly Token Usage */
      monthly_token_usage?: {
        [key: string]: unknown;
      } | null;
    };
    /** AccountPatchRequest */
    AccountPatchRequest: {
      /** Timezone */
      timezone?: string | null;
      /** Notification Preferences */
      notification_preferences?: {
        [key: string]: unknown;
      } | null;
    };
    /** ChatHistoryResponse */
    ChatHistoryResponse: {
      /** Conversation Id */
      conversation_id: string;
      /** Messages */
      messages: components["schemas"]["MessageSchema"][];
    };
    /** ChatMessageRequest */
    ChatMessageRequest: {
      /** Message */
      message: string;
      /** Conversation Id */
      conversation_id?: string | null;
    };
    /** ChatMessageResponse */
    ChatMessageResponse: {
      /** Conversation Id */
      conversation_id: string;
      /** Message */
      message: string;
      /** Agent Node */
      agent_node?: string | null;
      /** Proposed Plan */
      proposed_plan?: {
        [key: string]: unknown;
      } | null;
      /**
       * Requires User Action
       * @default false
       */
      requires_user_action: boolean;
    };
    /** GoalModifyRequest */
    GoalModifyRequest: {
      /** Message */
      message: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** MessageSchema */
    MessageSchema: {
      /** Id */
      id: string;
      /** Role */
      role: string;
      /** Content */
      content: string;
      /** Agent Node */
      agent_node?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** PatternPatchRequest */
    PatternPatchRequest: {
      /** User Override */
      user_override?: {
        [key: string]: unknown;
      } | null;
      /** Description */
      description?: string | null;
      /** Confidence */
      confidence?: number | null;
    };
    /** PhoneVerifyConfirmRequest */
    PhoneVerifyConfirmRequest: {
      /** Phone Number */
      phone_number: string;
      /** Code */
      code: string;
    };
    /** PhoneVerifySendRequest */
    PhoneVerifySendRequest: {
      /** Phone Number */
      phone_number: string;
    };
    /** RescheduleRequest */
    RescheduleRequest: {
      /** Message */
      message: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  send_message_api_v1_chat_message_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChatMessageRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChatMessageResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_history_api_v1_chat_history_get: {
    parameters: {
      query: {
        /** @description UUID of the conversation */
        conversation_id: string;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChatHistoryResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_goals_api_v1_goals__get: {
    parameters: {
      query?: {
        /** @description Filter by goal status */
        status?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          }[];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_goal_api_v1_goals__goal_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        goal_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  abandon_goal_api_v1_goals__goal_id__abandon_patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        goal_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  modify_goal_api_v1_goals__goal_id__modify_patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        goal_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GoalModifyRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChatMessageResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_goal_tasks_api_v1_goals__goal_id__tasks_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        goal_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          }[];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_today_tasks_api_v1_tasks_today_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          }[];
        };
      };
    };
  };
  get_task_api_v1_tasks__task_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  complete_task_api_v1_tasks__task_id__complete_patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  missed_task_api_v1_tasks__task_id__missed_patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  reschedule_task_api_v1_tasks__task_id__reschedule_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RescheduleRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChatMessageResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_overview_api_v1_analytics_overview_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  get_goals_progress_api_v1_analytics_goals_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown[];
        };
      };
    };
  };
  get_missed_by_category_api_v1_analytics_missed_by_cat_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown[];
        };
      };
    };
  };
  get_weekly_stats_api_v1_analytics_weekly_get: {
    parameters: {
      query?: {
        weeks?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown[];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_patterns_api_v1_patterns__get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown[];
        };
      };
    };
  };
  get_pattern_api_v1_patterns__pattern_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        pattern_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_pattern_api_v1_patterns__pattern_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        pattern_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  patch_pattern_api_v1_patterns__pattern_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        pattern_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PatternPatchRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_me_api_v1_account_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccountMeResponse"];
        };
      };
    };
  };
  patch_me_api_v1_account_me_patch: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AccountPatchRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  phone_verify_send_api_v1_account_phone_verify_send_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PhoneVerifySendRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  phone_verify_confirm_api_v1_account_phone_verify_confirm_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PhoneVerifyConfirmRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  whatsapp_opt_in_api_v1_account_whatsapp_opt_in_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  delete_account_api_v1_account__delete: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  export_account_api_v1_account_export_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  twilio_whatsapp_webhook_api_v1_webhooks_twilio_whatsapp_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  twilio_voice_webhook_api_v1_webhooks_twilio_voice_post: {
    parameters: {
      query: {
        task_id: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  trigger_location_api_v1_demo_trigger_location_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  echoconfig__echoconfig_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
}
